### ISSUE TITLE
Tasarım-Kod Geçişinin Yapılması

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#10]
Tasarım belgesi doğrultusunda kodlama yapılacaktır. Sorunsuz çalışan ama tam olmayan, bir nevi taslak bir program yaratılacaktır. Menü geçişleri üzerinde durulacaktır. @FatimaBetul ve @ahmetnas tarafından yürütülecektir, gerektiğinde diğer grup elemanları yardımcı olacaklardır.

**Comment by ahmetnas** [comment]
Düşünülen görsel tasarım koda çevrilerek üzerinde uygulanması planlanan geçiş düzeni, uyarı tabloları, hazırlıklarına başlanıldı.
