### ISSUE TITLE
Belgelerin ve Kodlamanın Kontrolü - Test Aşaması

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#11]
Hazırlanan belgelerde eksik olup olmadığı kontrol edilecektir, eksik varsa aşamalar baştan ele alınacaktır. Bu belgeler doğrultusunda kodlamanın doğru veya yeterli olup olmadığı kontrol edilecek ve onaylanacaktır. @MelikeBulut tarafından yürütülecektir, test sonucunun olumlu veya olumsuz olması durumu @salihtuc ve @EbruAlic'a bildirilecektir.

Aynı zamanda gereksinim belgesine destek olarak bir diagram hazırlanacaktır.

**Comment by MelikeBulut** [comment]
![961698_1423923351254892_184706796_n](https://cloud.githubusercontent.com/assets/7452873/6881189/8619624e-d55d-11e4-87f5-e21fd4e68c49.jpg)
![11081682_1423923327921561_803915800_n](https://cloud.githubusercontent.com/assets/7452873/6881191/86466fbe-d55d-11e4-8af4-8b45e7a78e34.jpg)
![11084499_1423923314588229_1333122722_n](https://cloud.githubusercontent.com/assets/7452873/6881193/8675a36a-d55d-11e4-8358-f60f3b90181b.jpg)
![11087187_1423923267921567_123020920_n](https://cloud.githubusercontent.com/assets/7452873/6881194/8676e87e-d55d-11e4-86a2-b9cf22da79a8.jpg)
![11096932_1423923304588230_1518261348_n](https://cloud.githubusercontent.com/assets/7452873/6881192/86739a5c-d55d-11e4-9a46-9f1d2004225b.jpg)

Contex of System ve Activity Diagram çalışmaları. Olabildiğince çeşitli diagramlar kullanılmaya çalışılıyor. Temeller oluşturulduktan sonra eksikler giderilecek, diagramlara son hali verilecektir.

**Comment by MelikeBulut** [comment]
![dsc_0403](https://cloud.githubusercontent.com/assets/7452873/6886322/8fb7911a-d641-11e4-827b-2b333dab53cb.JPG)
![dsc_0404](https://cloud.githubusercontent.com/assets/7452873/6886323/8fb83a20-d641-11e4-86b8-0b2cd7d0ada4.JPG)
![dsc_0405](https://cloud.githubusercontent.com/assets/7452873/6886324/8fcfabb0-d641-11e4-90f3-3c8040432f99.JPG)

İlk teslim için Test raporu hazırlıkları başlamış olup test planı üzerinde proje yöneticisi ile birlikte çalışılmaktadır.
