### ISSUE TITLE
Sınıf İskeletlerinin, Sistem Kodlarının Yazılması

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#12]
Gereksinim Belgesi ve Diagramlar yardımı ile elde edilen verilerin bir yapı halinde yazılması, sınıflar ve aralarındaki ilişkilerin kodlanması yapılacaktır. @FatimaBetul ve @ahmetnas önderliğinde ve @salihtuc'un desteğiyle yapılacaktır.

**Comment by FatimaBetul** [comment]
Belirtilen şartlara yönelik ön hazırlık yapıldı eldeki verilere dayanarak sınıf iskeleti oluşturulmaya başlandı.
