### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#14]
Çizimler elde yapılacak, bir kısmı bilgisayara geçilecek, kalan kısmı diğer grup üyeleri tarafından tamamlanacak.

@EbruAlic , @mert-serin , @salihtuc bu işten sorumlu olacaklar.

**Comment by EbruAlic** [comment]
Sequence diagram çizimleri elde hazırlandı. Her senaryoya uygun diagramlar, gerekli fonksiyonlar işlem aşamalarına göre belirtilerek çizildi.
