### ISSUE TITLE
Test Belgesi

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#16]
Şimdiye kadarki belgelerde neler eksik/yanlıştı?
Değerlendirilen koşullar nelerdi, ileride hangi koşullar değerlendirilecek?
Hangi yöntemler izlendi?

@MelikeBulut ve @salihtuc bu aşamanın sorumlularıdır.

**Comment by MelikeBulut** [comment]
Ayrıntılı olmayan test planı hazırlandı. Test case ler oluşturuldu. Şimdiye kadar teslim edilmiş olan gerkesinim belgesi için review ödevi ve diğer inceleme sonuçlarının da yer alacağı test raporu üzerinde çalışılmaya başlandı.
