### ISSUE TITLE
Requirements Specification

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#2]
Sistemle ilgili gereksinim ve kısıtlar.

**Comment by EbruAlic** [comment]
Sistemin gereksinimlerini detaylı bir şekilde ele alırken, sistem kısıtlarını da yazılım ve özel kısıtlar olmak üzere sistem analiz raporunu oluşturdum. Sistem tasarımcısı ve yazılım geliştirme uzmanları oluşturduğum bu rapor doğrultusunda ilerlediler. Ayrıca bu rapor test aşamasında da kullanılacaktır.
