### ISSUE TITLE
Domain Analysis

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#3]
Hangi sınıflar oluşturulacak? Değişkenler neler olacak? Tasarım-kod arasında köprü.

**Comment by ahmetnas** [comment]
Projenin Sistem Analisti @EbruAlic tarafından belirlenen gereksinimleri değerlendirerek, Proje Yönetimiz @salihtuc isteği doğrultusunda, projemizin tasarımcısı @mert-serin 'nin oluşturacağı tasarımı; @mert-serin ve @salihtuc 'tan dinleyip gerekli sınıfları oluşturdum. Her sınıfın kendi var olması gereken değişkenlerini ve değişken türlerini belirledim ve oluşturulması gereken sistem temel fonksiyonlarını oluşturmak üzere @FatimaBetul 'e teslim ettim.

**Comment by ahmetnas** [comment]
Projenin Sistem Analisti @EbruAlic tarafından belirlenen gereksinimleri değerlendirerek, Proje Yöneticisi @salihtuc isteği doğrultusunda, projemizin tasarımcısı @mert-serin 'nin oluşturacağı tasarımı; @mert-serin ve @salihtuc 'tan dinleyip gerekli sınıfları oluşturdum. Her sınıfın kendi var olması gereken değişkenlerini ve değişken türlerini belirledim. Class Diagram oluşturulması için hazır hale getirdim.
