### ISSUE TITLE
UML Class Diagram - UML Use Case Diagram

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#4]
Domain Analizi - Sistem Temel Fonksiyonları doğrultusunda hazırlanacak.

**Comment by ahmetnas** [comment]
Projenin Sistem Analisti @EbruAlic tarafından belirlenen gereksinimleri değerlendirerek, Proje Yönetimiz @salihtuc isteği doğrultusunda, projemizin tasarımcısı @mert-serin 'nin oluşturacağı tasarımı; @mert-serin ve @salihtuc 'tan dinleyip gerekli sınıfları oluşturdum. Her sınıfın kendi var olması gereken değişkenlerini ve değişken türlerini belirledim ve oluşturulması gereken sistem temel fonksiyonlarını oluşturmak üzere @FatimaBetul e teslim ettim.

**Comment by salihtuc** [comment]
@EbruAlic tarafından hazırlanan gereksinim belgesi ve @ahmetnas ve @FatimaBetul tarafından hazırlanan Domain Analizi ve Sistem Temel Fonksiyonları raporları doğrultusunda düzenleme işlemi yapıldı ve sınıf düzenini belirlemek adına UML Class Diagram, kullanıcı ve onların fonksiyonlarını/işlevlerini, birbirlerini nasıl etkilediklerini gösteren UML Use Case Diagram çizildi. 

Bu çizimler tasarım, kodlama ve test bölümlerinde baz alınacak temelleri açık ve kolay anlaşılır bir şekilde belirlemekte kullanılmak üzere tasarlandı.
