### ISSUE TITLE
Sistem Temel Fonksiyonları

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#5]
Sistemdeki kullanıcılar kimler? Hangi fonksiyonları/görevleri/işlemleri yönetiyorlar?

**Comment by FatimaBetul** [comment]
Sistem analisti tarafından hazırlan gereksinim belgesi analiz edildikten sonra  sistem kullanıcılarının yapabilecekleri işlemler belirlenerek sistem temel fonksiyonları raporu oluşturuldu.
