### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#6]
Kullanıcı arayüzü tasarımları.

**Comment by mert-serin** [comment]
Uygulamamız analistimiz @EbruAlic tarafından hazırlanan gereksinim belgesi ve proje yöneticimiz tarafından hazırlanan UML Diagramlardan yararlanarak tasarlandı. Sistemin kolay kullanılabilir ve programlanabilir olmasının yanında sistemin asıl kullanıcıları olacak Hacettepe Üniversitesi öğrencilerine danışarak insanlar tarafından en rahat kullanılacak sistem renkleri konusunda da mütabakata varıldı.
