### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#7]
Tüm aşamalar test edilir ve onaylanır; onaylanmazsa işlem baştan tekrar edilir.

**Comment by MelikeBulut** [comment]
Gereksinimlerin geçerliliğinin kontrolü aşamasında gereksinimler gerçeklik ve tutarlılık açısından kontrol edilerek eksiksiz hale getirilmeye çalışıldı. Sistem temel fonksiyonları, diagram çizimleri ve kullanıcı arayüzleri tasarımı incelendi. Bu bileşenlerdeki sorunlar giderildi.
