### ISSUE TITLE
Analiz Belgesinin Hazırlanması

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#8]
Kullanıcı gereksinimlerinin tamamı ve sistem gereksinimlerinin bir kısmı ele alınacak, diagramlar ile süslenecektir. @salihtuc ile birlikte yürütülecektir. Diğer grup elemanlarından da destek alınacaktır.

**Comment by EbruAlic** [comment]
Çalışmalarımıza paralel olarak devam edebilmek için Vad diagramı oluşturdum. Bu diagram ygular tarafından fonskiyonların belirlenmesinde kullanılmıştır. Ayrıca ileriki çalışmalarda diagramın eksikleri giderilecek ve yeni diagramlar eklenecektir.
![vad diagrami](https://cloud.githubusercontent.com/assets/11196872/6877678/ef6751b6-d4db-11e4-878d-0c506a262680.JPG)
