### ISSUE TITLE
Tasarım Belgesinin Hazırlanması

### ISSUE THREAD

**Issue by salihtuc** [salihtuc/BBM487-20142-11#9]
Kullanıcı arayüzleri tamamlanacak, analiz belgesi doğrultusunda kodlamayı ve güncellemeyi kolaylaştıracak sistem ve görünüm tasarımı yapılacaktır. Belge, program görüntüleri ve taslaklar ile süslenecektir. @salihtuc ile birlikte yürütülecektir. Aynı zamanda veritabanı yerine kullanılacak .csv dosyasının taslağı hazırlanacaktır. Diğer grup üyelerinin fikir ve destekleri de göz önünde bulundurulacaktır.

**Comment by mert-serin** [comment]
Kullanıcı arayüzleri ve csv dosyaları hazırlanıp grup arkadaşlarıyla paylaşıldı. Arayüz olarak iki renk arasında kararı grup arkadaşlarıyla beraber alacağız. Ayrıca tasarım planlaması olarak kullanmak üzere MVC'de anlaşıldı
